### ISSUE TITLE
Improve load times for the backgrounds

### ISSUE THREAD

**Issue by jonathandavis** [thefatherhoodwing/orion#3]
The large backgrounds are large. We should find a way to improve load times, or improve perceived performance. One way would be heavy blurring low-resolution versions that are scaled until the "real" image loads. Or we could just do heavy compression processing.

**Comment by cmdrkayll** [comment]
The index page is taking forever to load.  Do you know what might explain the difference in performance between the two index pages:

http://orion.ingenesis.net/
vs
http://www.onlineworkshop.com/fatherhood/index.shtml
