### ISSUE TITLE
Finalize Hosting

### ISSUE THREAD

**Issue by jonathandavis** [thefatherhoodwing/orion#8]
The site is currently hosted on a temporary staging server. We should probably move to a server that is paid for and controlled by someone in wing leadership.

**Comment by RandalphRoddleton** [comment]
Looking into some options now, the requirements being a balance of cost vs ease of use vs root access.

Given a preference, which is preferred - Ubuntu, Debian or CentOS?

**Comment by jonathandavis** [comment]
Ubuntu
